---
title: "Citations & re-uses"
output:
  html_document:
    toc: false
    toc_float: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
bibfile <- "papers.bib"
```

To cite the European COVID-19 Forecast Hub, please use:

[Sherratt, Katharine, et al. "Predictive performance of multi-model ensemble forecasts of COVID-19 across European nations." medRxiv (2022).](https://www.medrxiv.org/content/10.1101/2022.06.16.22276024)

Please [get in touch](contact.html) if you know or published an article using
data from the European Covid-19 Forecast Hub or mentioning it as a public health
tool.

```{r, results='asis'}
library(magrittr)
b <- tools::bibstyle(
  "by_year", 
  fmtPrefix = function(paper) "-", 
  .init = TRUE, 
  sortKeys = function(refs) rank(purrr::map_chr(unclass(refs), "year"))
)

bibtex::read.bib(bibfile) %>%
  purrr::keep(~ attr(unclass(.x)[[1]], "bibtype") %in% c("Article", "PhdThesis")) %>%
  sort(.bibstyle = "by_year", decreasing = TRUE) %>%
  purrr::map_chr(format, "html", .bibstyle = "by_year") %>%
  paste(collapse = "") %>%
  cat()
```

