---
title: "Forecast visualisation"
output:
  html_document:
    toc: false
    toc_float: false
---
<style>
div.main-container {
    max-width: none;
}
body{
    padding-bottom: 0px;
}
.title{
    display: none;
}

.main-content{
    padding-top: 45px;
    height: 100%
}
.alert {
  font-size: 15px;
}
</style>

<script>
var resize_iframe = function() {
    return function(){
        var textHeight = document.getElementById('limitations').clientHeight;
        var element = document.getElementById('vizFrame');
        element.style = 'height: calc(100vh - ' + (textHeight + 90) + 'px);'
    };
};
window.onload = resize_iframe();
window.onresize = resize_iframe();
</script>

<script type="text/javascript">
  const iframeSrc = "https://european-modelling-hubs.github.io/covid19-forecast-hub-europe-viz/";
  window.addEventListener("load", function(e) {
    const iframe = document.getElementById("vizFrame");
    if (iframe) {
      iframe.src = iframeSrc + window.location.search;
    }
  });
</script>
  
<script type="text/javascript">
  // read queryParams from iframe and rewrite current url
  var eventMethod = window.addEventListener
    ? "addEventListener"
    : "attachEvent";
  var eventer = window[eventMethod];
  var messageEvent = eventMethod === "attachEvent"
    ? "onmessage"
    : "message";

  eventer(messageEvent, function (e) {
    
    if (e.origin !== 'https://covid19-forecast-hub-europe.github.io') {
      return;
    }
    
    if (e.data.$type === 'queryParams') {
      window.history.replaceState(null, null, '?' + e.data.value);
      console.log("PARENT SETTING", e.data.value);
    }
    
  });
</script>

<p id="limitations">
Please be aware of the [limitations](background.html) when interpreting the forecasts. We recommend to focus on the ensemble which would be expected to give the most reliable forecasts. For horizons beyond one week case forecasts in particular can rapidly become unreliable, especially in times of changing non-pharmaceutical or dominant variants. The individual models that constitute the ensemble have been contributed by independent teams. They are shown for transparency but should not be taken on their own without fully acknowledging their assumptions and limitations and engaging with the listed authors.
</p>

<div class="alert alert-warning" font-size: 15px>
  <strong>Disclaimer:</strong><br>
  <ul>
    <li>Due to <strong>differences in surveillance systems and data sources</strong>, we recommend <strong>focusing on trends rather than on absolute numbers</strong> to provide an indicator of the current epidemiological situation.</li>
    <li>Please note that forecasts are a characterisation of the surveillance systems, and the <strong>forecasts will hence reflect the reported data</strong>.</li>
  </ul>
</div>

<div class="row">
  <iframe width="100%"
    style="height: calc(100vh - 237px);"
    id="vizFrame"
    src="https://european-modelling-hubs.github.io/covid19-forecast-hub-europe-viz/"
    frameborder="0"
    scrolling="no">
  </iframe>
</div>
